- name: Installing Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Copy expense config file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import Common Role- App Pre-requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq

  vars:
    app_dir: /usr/share/nginx/html
    component: frontend

- name: Start nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Import ELK Role- Filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat

- name: Import Prometheus- Node Exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter

- name: Import Grafana- Dashboard Creation
  ansible.builtin.import_role:
    name: grafana

- name: Generate Alert YML file
  ansible.builtin.template:
    src: alert-rules.yml
    dest: /tmp/{{component}}-{{env}}.yml

- name: Upload Alert File toS3
  ansible.builtin.shell: aws s3 cp /tmp/{{component}}-{{env}}.yml s3://min-prometheus-rule/{{component}}-{{env}}.yml
  #amazon.aws.s3_object:
    #bucket: min-prometheus-alert-rule
    #object: "{{component}}-{{env}}.yml"
    #src: /tmp/{{component}}-{{env}}.yml
    #mode: put

- name: Trigger Prometheus Reload job
  ansible.builtin.shell: curl -u {{ lookup('aws_ssm', 'jenkins.username', region='us-east-1' ) }}:{{ lookup('aws_ssm', 'jenkins.password', region='us-east-1' ) }} "http://172.31.40.227:8080/job/prometheus-reload/build?token=prometheus"

