format_version: 10
pipelines:
  Mutable_Deployment_FRONTEND:
    group: defaultGroup
    environment_variables:
      ENV: ""
      APP_VERSION: ""
      COMPONENT: frontend
    materials:
      deploy:
        git: http://github.com/devopsmins/expense-ansible
        shallow_clone: true
        auto_update: true
        branch: main
    stages:
    - dev:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
        jobs:
          deploy:
            timeout: 0
            tasks:
            - exec:
                command: echo
                arguments:
                  - "Deploying to Dev env"
                run_if: passed

    - qa:
        fetch_materials: false
        keep_artifacts: false
        clean_workspace: false
        approval:
            type: manual
        jobs:
          deploy:
            timeout: 0
            tasks:
              - exec:
                  command: echo
                  arguments:
                    - "Deploying to qa env"
                  run_if: passed

    - uat:
        fetch_materials: false
        keep_artifacts: false
        clean_workspace: false
        approval:
            type: manual
        jobs:
          deploy:
            timeout: 0
            tasks:
              - exec:
                  command: echo
                  arguments:
                    - "Deploying to uat env"
                  run_if: passed


    - prod:
        fetch_materials: false
        keep_artifacts: false
        clean_workspace: false
        approval:
            type: manual
        jobs:
          deploy:
            timeout: 0
            tasks:
              - exec:
                  command: echo
                  arguments:
                    - "Deploying to prod env"
                  run_if: passed
