- name: Delete old app content
  ansible.builtin.file:
    path: "{{ app_dir}}"
    state: absent

- name: create App Directory
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{app_user}}"
    group: "{{app_user}}"

#- name: Download and extract app content
 # ansible.builtin.unarchive:
  #  src: https://expense-artifacts.s3.amazonaws.com/{{ component }}.zip
   # dest: "{{ app_dir}}"
    #remote_src: yes

- name: Download and extract app content
  ansible.builtin.unarchive:
    src: https://{{ lookup('aws_ssm', 'artifactory.username', region='us-east-1' ) }}:{{ lookup('aws_ssm', 'artifactory.password', region='us-east-1' ) }}@artifactory.devopsmins.online:8081/artifactory/{{ project_name }}-{{ component }}/{{ project_name }}-{{ component }}-1.0.0.zip
    dest: "{{ app_dir}}"
    remote_src: yes